export const defaultSettings = {
  restaurantName: 'Nhà hàng CAS',
  legalName: 'Core Advanced Solutions',
  tagline: 'Restaurant Order Management',
  address: '127 Nguyễn Văn Linh, Quận 7, TP. Hồ Chí Minh',
  phone: '0900 123 456',
  email: 'hello@cas.vn',
  website: 'cas.vn',
  defaultArea: 'Sảnh chính',
  staffName: 'Nhân viên phục vụ',
  cashierName: 'Thu ngân CAS',
  customerName: 'Khách lẻ',
  guestCount: 2,
  vatRate: 0.1,
  serviceFeeRate: 0.05,
  discountAmount: 0,
  invoiceNote: 'Cảm ơn quý khách. Hẹn gặp lại!',
  activePaymentMethods: ['cash', 'card', 'qr'],
  visibleDashboardWidgets: ['revenue', 'orders', 'paymentMix', 'topItems', 'staff'],
};
