export const defaultSettings = {
  restaurantName: 'Nhà hàng CAS',
  legalName: 'CAS Restaurant',
  tagline: 'Phục vụ tận tâm',
  address: 'Chưa cập nhật địa chỉ',
  phone: 'Chưa cập nhật',
  email: 'Chưa cập nhật',
  website: 'Chưa cập nhật',
  defaultArea: 'Sảnh chính',
  staffName: 'Nhân viên phục vụ',
  cashierName: 'Thu ngân',
  customerName: 'Khách lẻ',
  guestCount: 2,
  vatRate: 0.1,
  serviceFeeRate: 0.05,
  discountAmount: 0,
  invoiceNote: 'Cảm ơn quý khách. Hẹn gặp lại!',
  activePaymentMethods: ['cash', 'card', 'qr'],
  visibleDashboardWidgets: ['revenue', 'orders', 'paymentMix', 'topItems', 'staff'],
};
